updated hover transition
ehsanullahhaidary/dribble-clone pull request #19
Opened 2024-10-04 06:50 UTC by Anush0108

changed the hover color and opacity.

 // Dribbble svg 
    &--svg{
      transition: all .2s ease-in-out;
    }
 &--svg {
      transition: all 0.2s ease-in-out;
      fill: #350716; // Default color (e.g., pink)
    }

    // dribbble svg hover section
    &--svg:hover {
      cursor: pointer;
      @include medium-920 {
        fill: #f92e0a;
        opacity: 0.8;
      }
    }

2024-10-04 07:48 UTC, successbyte requested changes
Could you please just change the `opacity: 0.6;` please and remove all other changes

2024-10-04 07:49 UTC, successbyte reviewed
Could you please just change the `opacity: 0.6;` please and remove all other changes

2024-10-04 08:08 UTC, Anush0108 commented
Updated the opacity to 0.6 also removed all the other changes

2024-10-05 07:59 UTC, successbyte approved these changes
Good thanks

2024-10-05 08:00 UTC, merged