[FIX] #22 Search transition and color
ehsanullahhaidary/dribble-clone pull request #24
Opened 2024-10-06 11:39 UTC by MiteshDalvi

I have resolved the search icon blinking animation. Actually there was an 3s infinite animation code written in header.scss file due to which the issue was coming. The search icon now has static animation and while hovering, it change to pink color without changing its opacity

https://github.com/user-attachments/assets/7204bf8f-4d0b-4d03-a7f5-e29a1c548bae

.

2024-10-07 10:40 UTC, successbyte reviewed
Please delete the keyframe related to the animation and check if its not used in another place
thanks

2024-10-07 10:40 UTC, successbyte commented on scss/_header.scss
>      @keyframes gradient-pulse {
Please delete the keyframe related to the animation and check if its not used in another place 
thanks

2024-10-07 10:40 UTC, successbyte requested changes
Please delete the keyframe related to the animation and check if its not used in another place
thanks

2024-10-08 15:40 UTC, MiteshDalvi commented
I have committed the changes.

2024-10-08 17:40 UTC, successbyte approved these changes
It's great thanks

2024-10-08 17:40 UTC, merged

2024-10-08 17:41 UTC, successbyte commented
Please give the repo a star 
and invite your friends if they are interested in their first contribution.
thanks